"""
main.py — Streamlit front-end for PsycAI.

Run with:  streamlit run main.py
Requires:  model.pkl in the same directory (generated by final.ipynb)
"""

import streamlit as st
import pandas as pd
from fn import refine, predict


# ---------------------------------------------------------------------------
# Time Spent encoding — must match the training encoding in final.ipynb
# ---------------------------------------------------------------------------

TIME_OPTIONS = {
    "Less than 1 hour":        0,
    "Between 1 and 2 hours":   1,
    "Between 2 and 3 hours":   2,
    "Between 3 and 4 hours":   3,
    "Between 4 and 5 hours":   4,
    "More than 5 hours":       5,
}


def main():
    st.set_page_config(page_title="PsycAI — Mental Health Survey", page_icon="🧠")
    st.title("🧠 PsycAI: Social Media & Mental Health Survey")
    st.markdown(
        "This tool uses a trained neural network to estimate potential mental health "
        "risk based on your social media usage patterns. It is **not** a clinical diagnosis."
    )

    if 'submitted' not in st.session_state:
        st.session_state.submitted = False

    if not st.session_state.submitted:
        with st.form("survey_form"):

            st.subheader("About You")
            col1, col2 = st.columns(2)
            with col1:
                name = st.text_input("Name (optional)")
                age  = st.number_input("Age", min_value=10, max_value=100, step=1, value=20)
            with col2:
                sex = st.selectbox("Sex", ["Male", "Female"])
                relationship_status = st.selectbox(
                    "Relationship Status",
                    ["Single", "In a relationship", "Married", "Divorced"]
                )

            occupation      = st.selectbox("Occupation", ["University Student", "School Student", "Salaried Worker", "Retired"])
            social_media_user = st.radio("Are you a social media user?", ["Yes", "No"], horizontal=True)
            platforms_used  = st.text_input("Platforms used (comma-separated, e.g. Instagram, TikTok)")

            st.markdown("---")
            st.subheader("Social Media Usage")
            time_spent_label = st.selectbox("Average time spent on social media per day", list(TIME_OPTIONS.keys()))
            time_spent = TIME_OPTIONS[time_spent_label]   # encode to 0–5

            st.markdown("---")
            st.subheader("Mental Health Questions")
            st.caption("Rate each item from 1 (Not at all) to 5 (Very much / Always).")

            col_a, col_b = st.columns(2)
            with col_a:
                st.markdown("**ADHD-related**")
                adhd_q1 = st.slider("Purposeless use of social media",        1, 5, 3)
                adhd_q2 = st.slider("Distracted by social media while busy",  1, 5, 3)
                adhd_q3 = st.slider("General ease of distraction",            1, 5, 3)
                adhd_q4 = st.slider("Difficulty concentrating on tasks",      1, 5, 3)

                st.markdown("**Anxiety-related**")
                anxiety_q1 = st.slider("Restlessness without social media",   1, 5, 3)
                anxiety_q2 = st.slider("Bothered by worries generally",       1, 5, 3)

            with col_b:
                st.markdown("**Self-Esteem-related**")
                self_esteem_q1 = st.slider("Frequency of comparing self to others online", 1, 5, 3)
                self_esteem_q2 = st.slider(
                    "How do those comparisons make you feel?\n(1 = Very Negative, 5 = Very Positive)",
                    1, 5, 3
                )
                self_esteem_q3 = st.slider("Seeking validation through social media",      1, 5, 3)

                st.markdown("**Depression-related**")
                depression_q1 = st.slider("Frequency of feeling depressed or down",        1, 5, 3)
                depression_q2 = st.slider("Fluctuation in interest in daily activities",   1, 5, 3)
                depression_q3 = st.slider("Frequency of sleep issues",                     1, 5, 3)

            submitted = st.form_submit_button("Submit Survey", use_container_width=True)

            if submitted:
                if sex not in ("Male", "Female"):
                    st.error("The current model supports Male / Female inputs only. Please select one.")
                    st.stop()

                data = {
                    "Time Spent": time_spent,   # encoded 0–5
                    "ADHD Q1": adhd_q1,
                    "ADHD Q2": adhd_q2,
                    "ADHD Q3": adhd_q3,
                    "ADHD Q4": adhd_q4,
                    "Anxiety Q1": anxiety_q1,
                    "Anxiety Q2": anxiety_q2,
                    "Self Esteem Q1":   self_esteem_q1,
                    "Self Esteem Q2":   self_esteem_q2,
                    "Self Esteem Q3":   self_esteem_q3,
                    "Depression Q1":    depression_q1,
                    "Depression Q2":    depression_q2,
                    "Depression Q3":    depression_q3,
                }

                df = pd.DataFrame([data])
                df = refine(df)
                outcome = predict(df)

                st.session_state.submitted = True
                st.session_state.outcome   = outcome
                st.rerun()

    if st.session_state.submitted:
        outcome = st.session_state.outcome
        st.subheader("Your Result")

        if outcome == 1:
            st.error(
                "⚠️ **Potential Mental Health Risk Detected**\n\n"
                "Your responses suggest patterns associated with anxiety, depression, "
                "reduced self-esteem, or attentional difficulties linked to social media use. "
                "This is **not a clinical diagnosis** — please consider speaking with a "
                "mental health professional for a proper evaluation."
            )
        else:
            st.success(
                "✅ **No Significant Risk Detected**\n\n"
                "Your responses do not indicate elevated mental health risk based on your "
                "reported social media usage patterns. Stay mindful of your digital habits!"
            )

        st.markdown("---")
        st.caption(
            "Model: MLP Neural Network (sklearn) · Dataset: ~480 survey responses · "
            "Accuracy: ~98.9% on hold-out test set · "
            "[Source Code](https://github.com/shlokye16/psycSMMI) · "
            "[Paper Preprint](https://zenodo.org/records/19244475) · "
            "[Research Article](https://medium.com/@shloky.1605/sk051606-psycsmmi-2025idk-5481a9d3181f)"
        )

        if st.button("Take the survey again"):
            st.session_state.submitted = False
            st.rerun()


if __name__ == "__main__":
    main()
